image: node
cache:
  paths:
  - node_modules/
  
stages:
  - test
  
test:
  stage: test
  script:
  - yarn install
  - yarn test:no-report
  
pages:
  script:
  - echo "USING PRE-BUILT DOCS"
  - mv docs/ public/
  artifacts:
    paths:
    - public
